export const SEARCH_LOCATIONS_BY_ID_START = 'SEARCH_LOCATIONS_BY_ID_START';
export const SEARCH_LOCATIONS_BY_ID_SUCCESS = 'SEARCH_LOCATIONS_BY_ID_SUCCESS';
export const SEARCH_LOCATIONS_BY_ID_FAIL = 'SEARCH_LOCATIONS_BY_ID_FAIL';

export const SEARCH_LOCATIONS_BY_TERM_START = 'SEARCH_LOCATIONS_BY_TERM_START';
export const SEARCH_LOCATIONS_BY_TERM_SUCCESS = 'SEARCH_LOCATIONS_BY_TERM_SUCCESS';
export const SEARCH_LOCATIONS_BY_TERM_FAIL = 'SEARCH_LOCATIONS_BY_TERM_FAIL';

export const SAVE_PERSONAL_INFO_SUCCESS = 'SAVE_PERSONAL_INFO_SUCCESS';


export const SUBMIT_INFORMATION_START = 'SUBMIT_INFORMATION_START';
export const SUBMIT_INFORMATION_SUCCESS = 'SUBMIT_INFORMATION_SUCCESS';
export const SUBMIT_INFORMATION_FAIL = 'SUBMIT_INFORMATION_FAIL';