export const SEARCH_LOCATIONS_BY_ID_START = 'SEARCH_LOCATIONS_BY_ID_START';
export const SEARCH_LOCATIONS_BY_ID_SUCCESS = 'SEARCH_LOCATIONS_BY_ID_SUCCESS';
export const SEARCH_LOCATIONS_BY_ID_FAIL = 'SEARCH_LOCATIONS_BY_ID_FAIL';

export const SEARCH_LOCATIONS_BY_TERM_START = 'SEARCH_LOCATIONS_BY_TERM_START';
export const SEARCH_LOCATIONS_BY_TERM_SUCCESS = 'SEARCH_LOCATIONS_BY_TERM_SUCCESS';
export const SEARCH_LOCATIONS_BY_TERM_FAIL = 'SEARCH_LOCATIONS_BY_TERM_FAIL';

export const RATE_LOCATION_START = 'RATE_LOCATION_START';
export const RATE_LOCATION_SUCCESS = 'RATE_LOCATION_SUCCESS';
export const RATE_LOCATION_FAIL = 'RATE_LOCATION_FAIL';